puzzle/puzzle.opnsense

docs/docsite/rst/development_guide.rst
plugins/module_utils/config_utils.py
tests/unit/plugins/module_utils/test_config_utils.py

In order to offer a easy way for future modules to manage the OPNsense `config.xml` this PR adds the `OPNsenseConfig` context manager. Usage of this utility for future modules is as follows:
```python3
with OPNsenseConfig() as config:
value = config["key"]
config["key"] = new_value
del config["key"]
config.save()
```
The idea is that config properties are accessible in a `dict` structure. Settings are accessible at the same positions as in the XML file under the root tag `opnsense`.
For example, firewall filter rules would look like this:
```xml
<opnsense>
...
<filter>
<rule>....</rule>
<rule>....</rule>
...
</filter>
</opnsense>
```
management of these rules using the `OPNsenseConfig`:
``` python3
with OPNsenseConfig() as config:
config["filter"].append(some_new_rule)
config.save()
```

Add OPNsenseConfig uitility with tests

---

docs/docsite/rst/development_guide.rst
galaxy.yml
plugins/modules/get_xml_tag.py

- Add example module
- Update developers-guide: Vagrant-Setup
Relates to #14

Add example-module

---

plugins/module_utils/config_utils.py

Currently, if an exception is occurring during a module execution within the context of a `OPNsenseConfig` object, python calls `__exit__` which results in a misleading error message `Config has changed. Cannot exit without saving.`.
If for example we try to update the config by modifying it but we did not specify `become: true` we get the following error message:
```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: RuntimeError: Config has changed. Cannot exit without saving.
fatal: [opnsense]: FAILED! 
````
By first checking the exception type, we can make sure there was no exception and then proceed with the check for a changed config. If there was an exception, we will return it's type and value:
```
TASK [test] …
```

improove OPNsenseConfig errorhandling

---

.github/workflows/ansible-test.yml

Since Ansible 2.15 dropped support for Python 3.6, we need to exclude this in order to pass integration tests (See [Job #266](https://github.com/puzzle/puzzle.opnsense/actions/runs/6609367088/job/17968292062) )

Exclude python 3.6 for tests on ansible devel (2.15)

---

docs/docsite/rst/development_guide.rst
galaxy.yml
plugins/module_utils/config_utils.py
plugins/module_utils/module_index.py
tests/unit/plugins/module_utils/test_config_utils.py

Since we intend to access module settings using XPaths, it no longer makes sense to use the translation layer from XML to dict. These changes refactor the `OPNsenseConfig` to use ElementTree directly. Since we also now use a version aware approach the `OPNsenseConfig` is now also scoped to module specific settings and therefore has been renamed to `OPNsenseModuleConfig`. 
See the changes to the docsite for usage examples of the refactored class.

Build back XML to dictionary translation layer

---

.pylintrc
molecule/system_settings_general/converge.yml
molecule/system_settings_general/molecule.yml
molecule/system_settings_general/verify.yml
plugins/module_utils/config_utils.py
plugins/module_utils/module_index.py
plugins/module_utils/opnsense_utils.py
plugins/modules/system_settings_general.py
tests/unit/plugins/module_utils/test_config_utils.py
tests/unit/plugins/module_utils/test_opnsense_utils.py

* add diff property to `OPNsenseConfig` class which returns a dict with the config diff as required by ansible to display diffs using the `--diff` flag
* add `config_utils` which handles the required actions to apply changes in the System -> Settings -> General view
* add `system_settings_general` module with the ability to set hostname and domain
:warning: depends on https://github.com/puzzle/puzzle.opnsense/pull/39

initial commit of the system_settings_general module

---

.github/ISSUE_TEMPLATE/module_request.md

In order to manage and plan module development we could use a template, which helps us write down module specifications.

Add a plugin request template

---

Makefile
docs/docsite/rst/development_guide.rst
plugins/module_utils/config_utils.py
plugins/modules/system_settings_general.py
tests/unit/plugins/module_utils/test_config_utils.py
tests/unit/plugins/module_utils/test_opnsense_utils.py
tests/unit/plugins/module_utils/test_version_utils.py
tests/unit/plugins/module_utils/test_xml_utils.py

We encountered the use case, where we need to use the same xpaths from our module_index.VERSION_MAP across different modules. Eg. the firewall_rules module will need information about interfaces, while we intend to implement an `interface`  module which will also require version tracking for those interface-related xpaths. To prevent the case where we will need to track the respective xpaths across multiple module blocks inside our VERSION_MAP, we introduced config_contexts. Each context contains its settings with the corresponding xpath, its php_configure_functions, and its php_requirements.

Module config uses confg contexts

---

plugins/modules/system_settings_general.py

`config.get` now returns a `xml.etree.ElementTree.Element` due to the possibility of nested values. To fix the conditional check we need the text value of the respective config options.

fix config return value

---

.github/workflows/ansible-test.yml

Ansible Core devel drops python 3.7 support: https://forum.ansible.com/t/ansible-core-devel-drops-support-for-python-3-7/4736

Drop ansible core devel python 3.7 support

---

.github/workflows/ansible-test.yml
plugins/module_utils/xml_utils.py
tests/unit/plugins/module_utils/test_xml_utils.py

These changes add a utility for ElementTree element comparison by value.
The default equality comparison eg. "element_1 == element_2" does not work since the objects are compared by reference by default:
```python
>>> from xml.etree.ElementTree import Element
>>> e1 = Element("test")
>>> e2 = Element("test")
>>> e1 == e2
False
```
This utility function allows for an equality check based on the element's tag, text, and attribute values

XML Utility: elements_equal

---

plugins/module_utils/config_utils.py

When we use `module.fail_json` in our modules, this will cause our config managers ` __exit__` function to raise an exception. This will cause Ansible to display a warning (`Module invocation had junk after the JSON data`):
```
TASK [Converge - Set preserve logs] **************************************************************************************************************************
[WARNING]: Module invocation had junk after the JSON data: Exception occurred: 1
fatal: [opnsense]: FAILED! => {"changed": false, "msg": "Parameter max_log_file_size_mb is not supported in OPNsense 23.1"}
```
This is probably ok if the error was caused by an unhandled exception, but it's not what we expect if we handle an error in our module and deliberately call `module.fail_json`. This PR fixes the by …

update cfg mgr exit method

---

plugins/module_utils/config_utils.py
tests/unit/plugins/module_utils/test_config_utils.py

There are some cases where a config option will not be present in the XML unless the respective option is configured in the ui. In this case, the `set` and `diff` methods will fail because `self._config_xml_tree.find(xpath)` will yield `None`. This PR fixes this by creating a new empty xml element at the expected path (in case of `set`) or by defining an empty value of the respective config option (in case of `diff`)

handle none existing xml elements

---

molecule/system_settings_general/molecule.yml
molecule/system_settings_logging/converge.yml
molecule/system_settings_logging/molecule.yml
molecule/system_settings_logging/verify.yml
plugins/module_utils/module_index.py
plugins/modules/system_settings_general.py
plugins/modules/system_settings_logging.py

Resolves https://github.com/puzzle/puzzle.opnsense/issues/52
Depends on the following PRs:
- https://github.com/puzzle/puzzle.opnsense/pull/90
- https://github.com/puzzle/puzzle.opnsense/pull/93
- https://github.com/puzzle/puzzle.opnsense/pull/92

initial version of the system_settings_logging module

---

plugins/module_utils/config_utils.py

When providing feedback due to a version not supporting a module setting, the `php_requirements` and `configure_functions` should be excluded in the exception message, since they are not relevant for the semantic usage of settings based on the OPNsense version.

Exclude php_requirements and configure_functions in settings support exception

---

changelogs/fragments/109-use-product-series-in-version-detection.yml
plugins/module_utils/version_utils.py

To avoid tracking OPNsense versions for every bugfix version (eg. 24.1.4) we can focus just on minor releases (eg. 24.1). 
This is achieved by detecting the OPNsense version using the 'product_series' attribute of the `opnsense-version -O` command output.
Changes have been successfully tested on all present molecule scenarios.
Resolves #108

Use 'product_series' for version detection

---

changelogs/fragments/112-fix-user-extra-attributes-in-system_access_users.yml
plugins/module_utils/system_access_users_utils.py
tests/unit/plugins/module_utils/test_system_access_users_utils.py

These changes handle additional user attributes that are not (yet) handled by the system_access_users module.
They are stored in a generic `Users.extra_attrs` field, and written back when writing the config.
Resolves #111

Fix user extra attributes in system_access_users

---

changelogs/fragments/117-remove-user-shell-attribute-as-enum.yml
plugins/module_utils/system_access_users_utils.py
tests/unit/plugins/module_utils/test_system_access_users_utils.py

Remove the UserLoginEnum type to prevent strict validation.
#116

Remove user shell attribute as enum

---

changelogs/fragments/124-fix-password-module-index-entry.yml
plugins/module_utils/module_index.py
plugins/module_utils/system_access_users_utils.py

This Change fixes:
* ModuleIndex: Password entry now matches configure_function structure
* system_access_users_utils: Updated dict calls in order to work with the newly introduced structure

Fix password module index entry

---

changelogs/fragments/129-include-plugin-interfaces-for-assignments.yml
plugins/module_utils/interfaces_assignments_utils.py

Those changes include all plugin devices (Bridge, VLAN, VXLAN ...etc ) in the interfaces_assignments module validation.
Relates to the mentioned issue in #125 .

Include plugin interfaces in interfaces_assignment module

---

changelogs/fragments/132-improve-exception-handling-in-opnsenseconfigcontext.yml
plugins/module_utils/config_utils.py

Currently exceptions raised within an OPNsenseModuleConfig context are 'swallowed' by our current `__exit__` implementation. These changes raise the occurring exception properly such that we get a usable stack trace and can identify the error at hand more easily.

Rework exception handling within OPNsenseModuleConfig

---

molecule/system_high_availability_settings/converge.yml
molecule/system_high_availability_settings/molecule.yml

Adjust sys_hasync converge tests to not mess w/ idempotency + add converge tests for idempotency

fix converge idempotency tests

---

changelogs/fragments/143-add-extra-attributes-to-firewall-rules.yml
molecule/firewall_rules/converge.yml
plugins/module_utils/firewall_rules_utils.py
tests/unit/plugins/module_utils/test_firewall_rules_utils.py

Firewall Rules do currently omit any other XML attributes that are not relevant to the FirewallRule dataclass and therefore delete them when writing them back to the config.xml. These changes are a fix for the FirewallRule related issues #138 and #139 .

Add extra attributes to firewall rules

---

molecule/firewall_rules/molecule.yml
molecule/interfaces_assignments/molecule.yml
molecule/system_access_users/molecule.yml
molecule/system_settings_general/molecule.yml
molecule/system_settings_logging/molecule.yml
plugins/module_utils/module_index.py

I think this should be all that is required to make 24.7 work. I couldn't get the molecule tests to run locally so if someone can test, that would be good.

Add 24.7 Support

---

changelogs/fragments/153-fix-system-settings-logging-24.7-support.yml
molecule/system_settings_logging/converge.yml
plugins/module_utils/module_index.py
plugins/modules/system_settings_logging.py

As showed in [this](https://github.com/opnsense/core/blob/master/src/opnsense/mvc/app/models/OPNsense/Syslog/Migrations/M1_0_2.php) syslog model migration, syslog settings have changed location in the XML config.

Fix logging settings module 24.7 support

---

changelogs/fragments/160-fix-user-removal.yml
plugins/module_utils/system_access_users_utils.py

As @GBBx pointed out, the deletion of the user object doesn't work as expected. The reason for this is that the generated `self.users` consists of converted user entries with the `uid` attribute, while the provided user does not have a `uid` attribute.
Since the name attribute of a user is unique, we don't need to compare the entire user object to find the user being deleted.

updated the way, users are compared while deletion

---

changelogs/fragments/164-fix-xml-element-comparison-util.yml
plugins/module_utils/xml_utils.py
tests/unit/plugins/module_utils/test_xml_utils.py

XML Element comparison util did not work as expected. I've noticed that the following test passed, while IMO should not have passed:
```
def test_elements_equal_with_children():
"""
Tests elements_equal function matches recursively equal elements.
"""
e1 = Element("test")
e1c1 = Element("child_1")
e1c1.text = "some_text"
e1c2 = Element("child_2")
e1c2.text = "some_text_as_well"
e1.extend([e1c1, e1c2])
e2 = Element("test")
e2c1 = Element("child_1")
e2c1.text = "some_text     \n"
e2c2 = Element("child_2")
e2c2.text = "\n   some_text     \n"
e2.extend([e2c1, e2c2])
assert xml_utils.elements_equal(e1, e2)
```
The `e1c2.text` should not have matched the content of the `e2c2.text` even when stripped from whitespaces.

Make XML element comparison util more generic
